CREATE TABLE IF NOT EXISTS medicine
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    expiration_date date NOT NULL,
    quantity int NOT NULL

);